name: Test
on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.27.x", "stable"]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
          cache: true

      - name: Check formatting
        shell: bash
        run: |
          files=( $(git ls-files -- '*.go') )
          unformatted=$(gofmt -l "${files[@]}")

          if [[ -n "$unformatted" ]]; then
            echo "The following Go files are not formatted:"
            echo "$unformatted"
            exit 1
          fi

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -v -race ./...
